version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3090:3090"
    depends_on:
      - backend
    env_file:
      - ../.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      # - "6005:6005" #remove this so it is only open to the internal network
    env_file:
      - ../.env
